openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
paths:
  /user/{id}:
    get:
      x-@id: http://myVoc.org/vocab#getUser
      summary: 'gets a user by its id'
      operationId: getCUser
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        "200":
          description: The user retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
components:
  schemas:
    User:
      type: object
      x-@id: http://myVoc.org/vocab#user
      properties:
        id:
          type: integer
          x-@type: https://schema.org/identifier
          x-@id: http://myVoc.org/vocab#userIdentifier
          format: int64
        firstName:
          type: string
          x-@type: https://schema.org/Text
          x-@id: http://myVoc.org/vocab#userName
        lastName:
          type: string
          x-@type: https://schema.org/Text
          x-@id: http://myVoc.org/vocab#userLastName
        email:
          type: string
          x-@type: https://schema.org/email
          x-@id: http://myVoc.org/vocab#userEmail
        age:
          type: integer
          format: int32
          x-@type: https://schema.org/Integer
          x-@id: http://myVoc.org/vocab#userAge
        bio:
          type: string
          x-@type: https://schema.org/Text
          x-@id: http://myVoc.org/vocab#userBio
        updatedAt:
          type: string
          format: date-time
          x-@type: https://schema.org/DateTime
          x-@id: http://myVoc.org/vocab#userUpdatedAt
  parameters:
    id:
        in: path
        name: id
        description: the id of the card to be deleted
        required: true
        schema:
          x-@type: https://schema.org/identifier
          x-@id: http://myVoc.org/vocab#userIdentifier
          type: integer
